name: Generate Code Lines Badge

on:
  push:
    branches:
      - main

jobs:
  count_lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count Lines of Code
        run: |
          total_lines=$(find . -name '*.py' -o -name '*.js' -o -name '*.java' -o -name '*.c' | xargs wc -l | tail -1 | awk '{print $1}')
          echo "Total Lines: $total_lines"
          echo "total_lines=$total_lines" >> $GITHUB_ENV
      - name: Update Badge
        uses: amannn/action-semantic-pull-request@v3
        with:
          custom: "lines:total-lines=$total_lines"

